### ISSUE TITLE
About the previous (gtk3) iteration of this repo

### ISSUE THREAD

**Issue by CliodynamicPragmatics** [natorsc/gui-python-pygobject-gtk4#7]
Hi, I remember that there was a Gtk3 version of this repo. What happened to it?

**Comment by natorsc** [comment]
Hello @CliodynamicPragmatics.

You are correct, there was content about Gtk 3 in this repository.

I started refactoring the repository for Gtk 4 and ended up removing the content relating to Gtk 3.

By my fault the content ended up only on my computer, thanks for reminding me.

I created a new repository: [https://github.com/natorsc/gui-python-pygobject-gtk3](https://github.com/natorsc/gui-python-pygobject-gtk3).

If you need help with something please let me know and thanks again 😀!

**Comment by natorsc** [comment]
Repository created (https://github.com/natorsc/gui-python-pygobject-gtk3).

**Comment by CliodynamicPragmatics** [comment]
Thanks a lot!
