### ISSUE TITLE
You are using Adw.ToastOverlay incorrectly("gui-python-pygobject-gtk4/src/gtk4-libadwaita-widgets/toast/MainWindow.py/")

### ISSUE THREAD

**Issue by qwersyk** [natorsc/gui-python-pygobject-gtk4#9]
![Group 1(1)](https://user-images.githubusercontent.com/81904181/174625404-4811e17a-2391-48ef-ab7b-a6c9645931f1.png)
Adw.ToastOverlay is a box in which you need to put an object (Adw.ToastOverlay.set_child(Gtk.Widget())), and after that you need to put Adw.Toast (ToastOverlay.add_toast(Adw.Toast())).
Code example:
self.ToastOverlay=Adw.ToastOverlay()
self.set_child(self.ToastOverlay)
self.ToastOverlay.set_child(Gtk.Label(label="Gtk.Widget"))
self.ToastOverlay.add_toast(Adw.Toast())
I hope I wrote and explained correctly.

**Comment by natorsc** [comment]
Thank you so much @qwersyk.

I had been reading the documentation and trying to understand this for a long time 😆.

Now with the image the widget made total sense to me .

I'll wait a few days to make the correction, if you make a pull request with the correction I'll do the merge.

**Comment by natorsc** [comment]
Fixed - [Commit](https://github.com/natorsc/gui-python-pygobject-gtk4/commit/76609fd9e6a071e905ceb48e99390b5d55656adb).
